// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"context"
	"database/sql"
	"github.com/gin-gonic/gin"
	"github.com/go-redis/redis/v8"
	"log"
	"net/http"
	"time"
	"week04/api"
	"week04/internal/data"
)

// Injectors from wire.go:

func InitResource() (*App, func(), error) {
	db, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := data.NewREDIS()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server, cleanup3, err := NewHttp()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup4, err := NewApp(db, client, server)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	HS *http.Server
	Db *sql.DB
	Rd *redis.Client
}

var Routes = map[string]func(ctx *gin.Context){
	"/create_asset": api.Hosts,
}

func NewHttp() (*http.Server, func(), error) {
	routes := gin.Default()

	registerRoutes(routes)

	hSrv := &http.Server{
		Addr:    "127.0.0.1:9999",
		Handler: routes,
	}
	clean := func() {
		ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
		if err := hSrv.Shutdown(ctx); err != nil {
			log.Fatal(err)
		}
		cancel()
	}
	return hSrv, clean, nil
}

// 注册路由函数
func registerRoutes(engine *gin.Engine) {
	for route, fn := range Routes {
		engine.POST(route, fn)
	}
}

func NewApp(d *sql.DB, r *redis.Client, h *http.Server) (*App, func(), error) {
	return &App{h, d, r}, func() {}, nil
}
